"""Nebula Wizard Framework — Post-Generation Finalizer."""

from __future__ import annotations
import re
from typing import Any, Optional

from prompt_toolkit import prompt
from prompt_toolkit.completion import WordCompleter

from pyregex.presentation.assistant.core.types import WizardResult
from pyregex.presentation.assistant.core.session import SessionContext
from pyregex.utils import ansi


class WizardFinalizer:
    """
    Handles post-generation actions after a wizard produces a pattern.

    Actions available:
    - Save to registry
    - Test against input
    - Edit the pattern inline
    - Explain the pattern (via AST engine)
    - Copy to clipboard
    - Export to file
    """

    def __init__(self, cli: Any):
        self.cli = cli

    def run(self, result: WizardResult, session: SessionContext) -> WizardResult:
        """Display post-generation menu and handle actions."""

        self._display_result(result)

        while True:
            print(f"\n{ansi.bold('¿Qué quieres hacer?')}")
            actions = [
                ("s", "Guardar en Registry"),
                ("t", "Probar con texto"),
                ("e", "Editar patrón"),
                ("x", "Explicar patrón"),
                ("c", "Copiar al portapapeles"),
                ("n", "Nueva generación"),
                ("q", "Salir"),
            ]
            for key, label in actions:
                print(f"  [{key}] {label}")

            completer = WordCompleter([a[0] for a in actions], ignore_case=True)
            choice = prompt("> ", completer=completer).strip().lower()

            if choice == "s":
                self._save_pattern(result, session)
            elif choice == "t":
                self._test_pattern(result.pattern)
            elif choice == "e":
                new_pattern = self._edit_pattern(result.pattern)
                if new_pattern:
                    result.pattern = new_pattern
                    self._display_result(result)
            elif choice == "x":
                self._explain_pattern(result.pattern)
            elif choice == "c":
                self._copy_to_clipboard(result.pattern)
            elif choice == "n":
                result.metadata["action"] = "new"
                return result
            elif choice == "q":
                return result
            else:
                print(ansi.error("Opción no válida"))

        return result

    def _display_result(self, result: WizardResult) -> None:
        """Display the generated pattern with examples."""
        print(f"\n{'━' * 55}")
        print(f"  {ansi.bold('PATRÓN GENERADO')}")
        print(f"  {ansi.regex_display(result.pattern)}")
        print(f"{'━' * 55}")

        if result.examples:
            print(f"\n  {ansi.bold('Ejemplos que coinciden:')}")
            for ex in result.examples[:5]:
                print(f"    {ansi.success('')} {ex}")

        if result.non_examples:
            print(f"\n  {ansi.bold('Ejemplos que NO coinciden:')}")
            for ex in result.non_examples[:3]:
                print(f"    {ansi.error('')} {ex}")

        if result.tags:
            print(f"\n  {ansi.dim('Tags:')} {', '.join(result.tags)}")

    def _save_pattern(self, result: WizardResult, session: SessionContext) -> None:
        """Save the pattern to the registry."""
        name = prompt("  Nombre: ").strip()
        if not name:
            print(ansi.error("Nombre vacío, no guardado"))
            return

        try:
            from pyregex.infrastructure.persistence.pattern_repository import (
                SavedPattern,
            )

            self.cli.pattern_repo.save(
                SavedPattern(
                    name=name,
                    pattern=result.pattern,
                    description=result.description
                    or f"Generated by {result.builder_name}",
                    tags=result.tags,
                )
            )
            print(ansi.success(f"Guardado como '{name}'"))
        except Exception as e:
            print(ansi.error(f"Error guardando: {e}"))

    def _test_pattern(self, pattern: str) -> None:
        """Test the pattern against user-provided text."""
        text = prompt("  Texto a probar: ").strip()
        if not text:
            return
        try:
            rx = re.compile(pattern)
            matches = list(rx.finditer(text))
            if matches:
                print(
                    ansi.success(f"  {len(matches)} coincidencia(s) encontrada(s):")
                )
                for m in matches[:10]:
                    print(f"    [{m.start()}-{m.end()}] '{m.group()}'")
            else:
                print(ansi.error("  Sin coincidencias"))
        except re.error as e:
            print(ansi.error(f"  Error en regex: {e}"))

    def _edit_pattern(self, pattern: str) -> Optional[str]:
        """Let user edit the pattern inline."""
        print(f"  {ansi.dim('Patrón actual:')} {pattern}")
        new = prompt("  Nuevo patrón (Enter para mantener): ").strip()
        if new:
            try:
                re.compile(new)
                print(ansi.success("  Patrón válido"))
                return new
            except re.error as e:
                print(ansi.error(f"  Patrón inválido: {e}"))
                return None
        return None

    def _explain_pattern(self, pattern: str) -> None:
        """Explain the pattern using the AST engine."""
        try:
            from pyregex.domain.explain.engine import AdvancedExplainer

            explainer = AdvancedExplainer()
            result = explainer.explain(pattern)

            if hasattr(result, "semantic_lines") and result.semantic_lines:
                print(f"\n  {ansi.bold('Explicación:')}")
                for line in result.semantic_lines:
                    print(f"    {ansi.success('')} {line}")
            else:
                print(f"\n  {ansi.dim('Sin explicación disponible para este patrón')}")
        except Exception as e:
            print(ansi.error(f"  Error explicando: {e}"))

    def _copy_to_clipboard(self, pattern: str) -> None:
        """Copy pattern to clipboard. Tries multiple methods."""
        import subprocess
        import shutil

        # Method 1: xclip
        if shutil.which("xclip"):
            try:
                proc = subprocess.Popen(
                    ["xclip", "-selection", "clipboard"], stdin=subprocess.PIPE
                )
                proc.communicate(pattern.encode())
                if proc.returncode == 0:
                    print(ansi.success("  Copiado al portapapeles (xclip)"))
                    return
            except Exception:
                pass

        # Method 2: xsel
        if shutil.which("xsel"):
            try:
                proc = subprocess.Popen(
                    ["xsel", "--clipboard", "--input"], stdin=subprocess.PIPE
                )
                proc.communicate(pattern.encode())
                if proc.returncode == 0:
                    print(ansi.success("  Copiado al portapapeles (xsel)"))
                    return
            except Exception:
                pass

        # Method 3: wl-copy (Wayland)
        if shutil.which("wl-copy"):
            try:
                proc = subprocess.Popen(["wl-copy"], stdin=subprocess.PIPE)
                proc.communicate(pattern.encode())
                if proc.returncode == 0:
                    print(ansi.success("  Copiado al portapapeles (wl-copy)"))
                    return
            except Exception:
                pass

        # Method 4: pbcopy (macOS)
        if shutil.which("pbcopy"):
            try:
                proc = subprocess.Popen(["pbcopy"], stdin=subprocess.PIPE)
                proc.communicate(pattern.encode())
                if proc.returncode == 0:
                    print(ansi.success("  Copiado al portapapeles (pbcopy)"))
                    return
            except Exception:
                pass

        # Method 5: OSC 52 terminal escape sequence (works on most modern terminals)
        import base64
        encoded = base64.b64encode(pattern.encode()).decode()
        print(f"\033]52;c;{encoded}\a", end="", flush=True)
        print(ansi.success("  Copiado al portapapeles (terminal OSC 52)"))

