from abc import ABC, abstractmethod
from typing import Any, List, Optional

# Interfaces use Any/Optional to avoid circular imports with concrete implementations.
class PatternRepositoryPort(ABC):
    @abstractmethod
    def save(self, pattern: Any) -> None: ...
    @abstractmethod
    def get(self, name: str) -> Optional[Any]: ...
    @abstractmethod
    def list_all(self, tag: Optional[str] = None, scope: Optional[str] = None) -> List[Any]: ...
    @abstractmethod
    def delete(self, name: str) -> bool: ...

class ConfigRepositoryPort(ABC):
    @abstractmethod
    def load(self) -> Any: ...
    @abstractmethod
    def save(self, config: Any) -> None: ...
    
class HistoryRepositoryPort(ABC):
    @abstractmethod
    def add(self, command: str, success: bool) -> None: ...
    @abstractmethod
    def get_all(self) -> List[Any]: ...
    @abstractmethod
    def clear(self) -> None: ...
