from pyregex.infrastructure.registry.commands.list.query.builder import ListQuery
from pyregex.infrastructure.registry.commands.list.filtering.filter_engine import (
    FilterEngine,
)
from pyregex.infrastructure.registry.commands.list.sorting.sorter import Sorter
from pyregex.infrastructure.registry.commands.list.grouping.grouper import Grouper
from pyregex.infrastructure.registry.commands.list.pagination.paginator import Paginator
from pyregex.infrastructure.registry.commands.list.output.views import (
    SimpleView,
    DetailedView,
    CompactView,
    GroupedView,
)
from pyregex.infrastructure.registry.search.engine import SearchEngine
from pyregex.utils import ansi


class ListController:
    """Orchestrates the discovery subsystem pipeline."""

    def __init__(self, search_engine: SearchEngine):
        self.filter_engine = FilterEngine(search_engine)
        self.sorter = Sorter()
        self.grouper = Grouper()
        self.paginator = Paginator()

        self.views = {
            "simple": SimpleView(),
            "compact": CompactView(),
            "detailed": DetailedView(),
            "tree": GroupedView(),  # Grouped View
        }

    def execute(self, query: ListQuery) -> str:
        # 1. Pipeline Execution
        patterns = self.filter_engine.execute(query)
        sorted_patterns = self.sorter.sort(patterns, query.sort_by)
        grouped_data = self.grouper.group(sorted_patterns, query.group_by)

        # Pagination handling depends on if it's grouped or flat.
        # For simplicity in UX, if we group, we might paginate keys or elements.
        # For grouped/tree views, pagination is tricky. Let's pass the whole dict directly if it's grouped.
        if query.group_by:
            # Group views (Tree) handle the whole dictionary directly to avoid disjointed category headers
            pagination_data = {
                "items": grouped_data,
                "total": len(sorted_patterns),
                "page": 1,
                "limit": query.limit,
                "has_next": False,
            }
        else:
            # Flat views grab from the "results" default key generated by grouper
            flat_list = grouped_data.get("results", [])
            pagination_data = self.paginator.paginate_flat(
                flat_list, query.page, query.limit
            )

        # View Resolution
        view = self.views.get(query.view_mode, self.views["simple"])

        # Validation checks on view vs data
        if query.group_by and query.view_mode != "tree":
            # Force tree view if grouped
            view = self.views["tree"]
        elif not query.group_by and query.view_mode == "tree":
            # Provide basic simple view if user asked for tree but no group provided
            view = self.views["simple"]

        rendered = view.render(pagination_data)

        # Meta footer
        footer = ""
        total = pagination_data.get("total", 0)
        if total > 0 and not query.group_by:
            footer = f"\n{ansi.dim(f'Showing {len(pagination_data.get('items', []))} of {total} patterns.')}"

        return rendered + footer
